alias: Bed Room Bug Trap Controller
description: ""
triggers:
  - entity_id: input_boolean.bedroom_bug_trap_cycle_active
    to: "on"
    id: start
    trigger: state
  - entity_id: input_boolean.bedroom_bug_trap_cycle_active
    to: "off"
    id: stop
    trigger: state
  - event_type: timer.finished
    event_data:
      entity_id: timer.bedroom_bug_trap_cycle
    id: timer_finished
    trigger: event
  - event: start
    id: startup
    trigger: homeassistant
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: start
        sequence:
          - variables:
              next_duration: >
                {{ duration_long if
                is_state('switch.third_reality_inc_3rsp02028bz','on')
                   else duration_short }}
          - target:
              entity_id: switch.third_reality_inc_3rsp02028bz
            action: switch.turn_on
          - target:
              entity_id: timer.bedroom_bug_trap_cycle
            data:
              duration: "{{ next_duration }}"
            action: timer.start
      - conditions:
          - condition: trigger
            id: timer_finished
        sequence:
          - variables:
              is_on: "{{ is_state('switch.third_reality_inc_3rsp02028bz','on') }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ is_on }}"
                sequence:
                  - target:
                      entity_id: switch.third_reality_inc_3rsp02028bz
                    action: switch.turn_off
                  - target:
                      entity_id: timer.bedroom_bug_trap_cycle
                    data:
                      duration: "{{ duration_short }}"
                    action: timer.start
              - conditions:
                  - condition: template
                    value_template: "{{ not is_on }}"
                sequence:
                  - target:
                      entity_id: switch.third_reality_inc_3rsp02028bz
                    action: switch.turn_on
                  - target:
                      entity_id: timer.bedroom_bug_trap_cycle
                    data:
                      duration: "{{ duration_long }}"
                    action: timer.start
      - conditions:
          - condition: trigger
            id: stop
        sequence:
          - target:
              entity_id: timer.bedroom_bug_trap_cycle
            action: timer.cancel
          - target:
              entity_id: switch.third_reality_inc_3rsp02028bz
            action: switch.turn_off
      - conditions:
          - condition: trigger
            id: startup
          - condition: state
            entity_id: input_boolean.bedroom_bug_trap_cycle_active
            state: "on"
        sequence:
          - variables:
              duration: >
                {{ duration_long
                   if is_state('switch.third_reality_inc_3rsp02028bz', 'on')
                   else duration_short }}
          - action: timer.start
            target:
              entity_id: timer.bedroom_bug_trap_cycle
            data:
              duration: "{{ duration }}"
variables:
  duration_long: "02:00:00"
  duration_short: "00:10:00"
mode: single