alias: Bed Room Humidifier Control Presence Based
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.ble_humidity_e5575839a12c
      - binary_sensor.bedroom_occupied_stable
  - trigger: homeassistant
    event: start
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ states('sensor.ble_humidity_e5575839a12c') | float(0) >=
              humidity_high }}
        sequence:
          - action: fan.turn_off
            metadata: {}
            target:
              entity_id: fan.b_humidifier_fan
            data: {}
      - conditions:
          - condition: state
            entity_id: binary_sensor.bedroom_occupied_stable
            state:
              - "on"
          - condition: template
            value_template: >-
              {{ states('sensor.ble_humidity_e5575839a12c') | float(0) <=
              humidity_low }}
        sequence:
          - action: fan.turn_on
            metadata: {}
            target:
              entity_id: fan.b_humidifier_fan
            data:
              percentage: 100
      - conditions:
          - condition: state
            entity_id: binary_sensor.bedroom_occupied_stable
            state:
              - "off"
        sequence:
          - action: fan.turn_off
            metadata: {}
            target:
              entity_id: fan.b_humidifier_fan
            data: {}
variables:
  humidity_low: 33
  humidity_high: 35
mode: single