alias: Office Bug Trap Controller
description: ""
triggers:
  - entity_id: input_boolean.office_bug_trap_cycle_active
    to: "on"
    id: start
    trigger: state
  - entity_id: input_boolean.office_bug_trap_cycle_active
    to: "off"
    id: stop
    trigger: state
  - event_type: timer.finished
    event_data:
      entity_id: timer.office_bug_trap_cycle
    id: timer_finished
    trigger: event
  - event: start
    id: startup
    trigger: homeassistant
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: stop
        sequence:
          - target:
              entity_id: timer.office_bug_trap_cycle
            action: timer.cancel
          - target:
              entity_id: switch.third_reality_inc_3rsp02028bz_4
            action: switch.turn_off
      - conditions:
          - condition: trigger
            id: start
        sequence:
          - target:
              entity_id: switch.third_reality_inc_3rsp02028bz_4
            action: switch.turn_on
          - target:
              entity_id: timer.office_bug_trap_cycle
            data:
              duration: "{{ duration_on }}"
            action: timer.start
      - conditions:
          - condition: trigger
            id: startup
          - condition: state
            entity_id: input_boolean.office_bug_trap_cycle_active
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: switch.third_reality_inc_3rsp02028bz_4
                    state: "on"
                sequence:
                  - target:
                      entity_id: timer.office_bug_trap_cycle
                    data:
                      duration: "{{ duration_on }}"
                    action: timer.start
              - conditions:
                  - condition: state
                    entity_id: switch.third_reality_inc_3rsp02028bz_4
                    state: "off"
                sequence:
                  - target:
                      entity_id: timer.office_bug_trap_cycle
                    data:
                      duration: "{{ duration_off }}"
                    action: timer.start
      - conditions:
          - condition: trigger
            id: timer_finished
          - condition: state
            entity_id: input_boolean.office_bug_trap_cycle_active
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: switch.third_reality_inc_3rsp02028bz_4
                    state: "on"
                sequence:
                  - target:
                      entity_id: switch.third_reality_inc_3rsp02028bz_4
                    action: switch.turn_off
                  - target:
                      entity_id: timer.office_bug_trap_cycle
                    data:
                      duration: "{{ duration_off }}"
                    action: timer.start
              - conditions:
                  - condition: state
                    entity_id: switch.third_reality_inc_3rsp02028bz_4
                    state: "off"
                sequence:
                  - target:
                      entity_id: switch.third_reality_inc_3rsp02028bz_4
                    action: switch.turn_on
                  - target:
                      entity_id: timer.office_bug_trap_cycle
                    data:
                      duration: "{{ duration_on }}"
                    action: timer.start
variables:
  duration_on: "01:00:00"
  duration_off: "00:10:00"
mode: single